baseURL: "https://windypath.com/"
title: 风萧古道 - 勤学苦练，年复一年
paginate: 5
theme: PaperMod

Copyright: "Windypath 风萧古道 **For Chinese Software**. [闽ICP备15016446号-3](https://beian.miit.gov.cn/)"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Windypath
  description: "For Chinese Software"
  keywords: [Blog, Windypath, PaperMod]
  author: JohnathanLin
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Windypath"
    # icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "勤学苦练，年复一年。"
    Content: "**Study And Practice, Years Of It.**"

  socialIcons:
    - name: github
      url: "https://github.com/JohnathanLin"
    - name: twitter
      url: "https://twitter.com/JohnathanLin427"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
languages:
  zh:
    languageName: 点击这里切换中文网站
    weight: 1
    title: 风萧古道 - 勤学苦练，年复一年
    description: 为了中国软件而奋斗
    params: 
      homeInfoParams:
        Title: "\U0001F44B 欢迎光临，我是凌虚"
        Content: "本站只分享软件技术内容，希望您可以在这里拓展视野，一起进步。"

    label:
      text: "风萧古道"
      # icon: /apple-touch-icon.png
      iconHeight: 35
    menu:
      main:
        - identifier: archives
          name: 归档
          url: /archives/
          weight: 10
        - identifier: categories
          name: 分类
          title: 分类
          url: /categories/
          weight: 11
        - identifier: tags
          name: 标签
          url: /tags/
          weight: 12
        - identifier: 关于
          name: 关于
          url: /about/
          weight: 13
        - identifier: mybooks
          name: 藏书
          url: /mybooks/
          weight: 18
        - identifier: myfriends
          name: 朋友
          url: /myfriends/
          weight: 19
        - identifier: search
          name: 搜索
          url: /search/
          weight: 20
    
    

  en:
    languageName: Switch to English Page
    weight: 2
    title: WindyPath - For Chinese Software
    description: For Chinese Software
    params: 
      homeInfoParams:
        Title: "\U0001F44B Hi, I'm Johnathan, Nice to meet you."
        Content: "Only software technique articles are in this website. I hope you can get improved here."

    
    menu:
      main:
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 10
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 11
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 12
        - identifier: about
          name: About
          url: /about/
          weight: 13
        - identifier: mybooks
          name: My Books
          url: /mybooks/
          weight: 18
        - identifier: myfriends
          name: My Friends
          url: /myfriends/
          weight: 19
        - identifier: search
          name: Search
          url: /search/
          weight: 20


defaultContentLanguage: zh

markup:
  goldmark:
    renderer:
      unsafe: true